export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#FF9801',
    accentRed: '#FF9801',
    accentPink: '#F96165',
    resprimary: '#A134F6',
  };

  export const InventoryItems = [
    {
      name: 'Fruits',
      image: require('../assets/fruit/fruit.jpg'),
      items: [
        {
          name: 'Apple',
          ID: 120928102910,
          rating: '5.0',
          Qty: '10 kg', 
          price: 199,
          isTopOfTheWeek: true,
          image: require('../assets/fruit/apple.jpg'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
        
        },
        {
          name: 'Orange',
          ID: 15120129010,
          Qty: '10 kg', 
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../assets/fruit/redOrange.png'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
         
        },
        {
          name: 'Banana',
          ID: 250210219910,
          Qty: '10 kg', 
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../assets/fruit/banana.png'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
         
        },
      ],
    },
    {
      name: 'Vegetable',
      image: require('../assets/veg/veg.jpg'),
      items: [
        {
          name: 'Onion',
          ID: 252901921020,
          Qty: '10 kg', 
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../assets/veg/onion.png'),
          size: 'Large 14"',
          crust: 'Thin Crust',
          delivery: 30,
       
        },
        {
          name: 'Carrot',
          ID: 300290122180,
          Qty: '10 kg', 
          rating: '4.5',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../assets/veg/carrot.png'),
          size: 'Large 16"',
          crust: 'Thin Cheese',
          delivery: 25,
       
        },
        {
          name: 'Garlic',
          ID: 351290129210,
          Qty: '10 kg', 
          rating: '4.2',
          price: 499,
          isTopOfTheWeek: false,
          image: require('../assets/veg/garlic.png'),
          size: 'Large 15"',
          crust: 'Thin Crust',
          delivery: 45,
       
        },
      ],
    },
    {
      name: 'Meat',
      image: require('../assets/meat/meat.jpg'),
      items: [
        {
          name: 'Chicken',
          ID: 20182301920,
          Qty: '10 kg', 
          rating: '5.0',
          price: 299,
          isTopOfTheWeek: true,
          image: require('../assets/meat/chicken.png'),
          size: 'Medium Glass',
          crust: 'Small Ice',
          delivery: 10,
         
        },
        {
          name: 'Lamb Meat',
          ID: 50172637120,
          Qty: '10 kg', 
          rating: '4.5',
          price: 199,
          isTopOfTheWeek: false,
          image: require('../assets/meat/lambmeat.png'),
          size: 'LArge Glass',
          crust: 'Large Ice',
          delivery: 8,
          
        },
        {
          name: 'Goat Meat',
          ID: 15082191219,
          Qty: '10 kg', 
          rating: '4.2',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../assets/meat/goatmeat.png'),
          size: 'Large Glass',
          crust: 'Small Ice',
          delivery: 5,
         
        },
      ],
    },
    {
        name: 'SeaFood',
        image: require('../assets/Fish/seafood1.png'),
        items: [
            {
                name: 'Atlantic Fish',
                ID: 120928102910,
                rating: '5.0',
                Qty: '10 kg', 
                price: 199,
                isTopOfTheWeek: true,
                image: require('../assets/Fish/atlanticFish.png'),
                size: 'Large 8"',
                crust: 'Thick Crust',
                delivery: 25,
              
              },
          {
            name: 'Crab',
            ID: 120928102910,
            rating: '5.0',
            Qty: '10 kg', 
            price: 199,
            isTopOfTheWeek: true,
            image: require('../assets/Fish/crab.png'),
            size: 'Large 8"',
            crust: 'Thick Crust',
            delivery: 25,
          
          },
          {
            name: 'Shrimp',
            ID: 15120129010,
            Qty: '10 kg', 
            rating: '4.5',
            price: 99,
            isTopOfTheWeek: false,
            image: require('../assets/Fish/shrimp.png'),
            size: 'Large 12"',
            crust: 'Thick Crust',
            delivery: 20,
           
          },
          {
            name: 'Lobster',
            ID: 250210219910,
            Qty: '10 kg', 
            rating: '4.2',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/Fish/lobster.png'),
            size: 'Large 10"',
            crust: 'Thick Crust',
            delivery: 35,
           
          },
        ],
      },
      {
        name: 'Spices',
        image: require('../assets/spices/spices.png'),
        items: [
          {
            name: 'Salt',
            ID: 120928102910,
            rating: '5.0',
            Qty: '10 kg', 
            price: 199,
            isTopOfTheWeek: true,
            image: require('../assets/spices/salt.png'),
            size: 'Large 8"',
            crust: 'Thick Crust',
            delivery: 25,
          
          },
          {
            name: 'Chilli Powder',
            ID: 15120129010,
            Qty: '10 kg', 
            rating: '4.5',
            price: 99,
            isTopOfTheWeek: false,
            image: require('../assets/spices/chillipowder.png'),
            size: 'Large 12"',
            crust: 'Thick Crust',
            delivery: 20,
           
          },
          {
            name: 'Turmeric Powder',
            ID: 250210219910,
            Qty: '10 kg', 
            rating: '4.2',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/spices/turmericpowder.png'),
            size: 'Large 10"',
            crust: 'Thick Crust',
            delivery: 35,
           
          },
          {
            name: 'Black Pepper',
            ID: 250210219910,
            Qty: '10 kg', 
            rating: '4.2',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/spices/blackpepper.png'),
            size: 'Large 10"',
            crust: 'Thick Crust',
            delivery: 35,
           
          },
          {
            name: 'Cardamom',
            ID: 250210219910,
            Qty: '10 kg', 
            rating: '4.2',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/spices/cardamom.png'),
            size: 'Large 10"',
            crust: 'Thick Crust',
            delivery: 35,
           
          },
          {
            name: 'Cloves',
            ID: 250210219910,
            Qty: '10 kg', 
            rating: '4.2',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/spices/cloves.png'),
            size: 'Large 10"',
            crust: 'Thick Crust',
            delivery: 35,
           
          },
       
        ],
      },
  ];

  export const Categories = [
    {
      name: 'Fruits',
      items: [
        {
          name: 'Ahmed',
          ID: 120928102910,
          rating: '5.0',
          Qty: '10 kg', 
          price: 199,
          isTopOfTheWeek: true,
          image: require('../assets/images/user13.jpg'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
        },
        {
          name: 'Ali',
          ID: 15120129010,
          Qty: '10 kg', 
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../assets/images/user2.jpg'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
        },
        {
          name: 'Usman',
          ID: 250210219910,
          Qty: '10 kg', 
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../assets/images/user3.jpg'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
         
        },
        {
            name: 'Asif',
            ID: 50172637120,
            Qty: '10 kg', 
            rating: '4.5',
            price: 199,
            isTopOfTheWeek: false,
            image: require('../assets/images/user12.jpg'),
            size: 'LArge Glass',
            crust: 'Large Ice',
            delivery: 8,
            
          },
    
      ],
    },
    {
      name: 'Vegetable',
      items: [
        {
          name: 'Wasim',
          ID: 252901921020,
          Qty: '10 kg', 
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../assets/images/user4.jpg'),
          size: 'Large 14"',
          crust: 'Thin Crust',
          delivery: 30,
       
        },
        {
          name: 'Saad',
          ID: 300290122180,
          Qty: '10 kg', 
          rating: '4.5',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../assets/images/user15.jpg'),
          size: 'Large 16"',
          crust: 'Thin Cheese',
          delivery: 25,
       
        },

        {
          name: 'Shehzad',
          ID: 351290129210,
          Qty: '10 kg', 
          rating: '4.2',
          price: 499,
          isTopOfTheWeek: false,
          image: require('../assets/images/user6.jpg'),
          size: 'Large 15"',
          crust: 'Thin Crust',
          delivery: 45,
       
        },
        {
            name: 'Momin',
            ID: 300290122180,
            Qty: '10 kg', 
            rating: '4.5',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/images/user12.jpg'),
            size: 'Large 16"',
            crust: 'Thin Cheese',
            delivery: 25,
         
          },
      ],
    },

    {
        name: 'Meat',
        items: [
          {
            name: 'Waqar',
            ID: 252901921020,
            Qty: '10 kg', 
            rating: '5.0',
            price: 199,
            isTopOfTheWeek: true,
            image: require('../assets/images/user14.jpg'),
            size: 'Large 14"',
            crust: 'Thin Crust',
            delivery: 30,
         
          },
          {
            name: 'Momin',
            ID: 300290122180,
            Qty: '10 kg', 
            rating: '4.5',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/images/user12.jpg'),
            size: 'Large 16"',
            crust: 'Thin Cheese',
            delivery: 25,
         
          },
          {
            name: 'Usman',
            ID: 250210219910,
            Qty: '10 kg', 
            rating: '4.2',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/images/user3.jpg'),
            size: 'Large 10"',
            crust: 'Thick Crust',
            delivery: 35,
           
          },
          {
              name: 'Asif',
              ID: 50172637120,
              Qty: '10 kg', 
              rating: '4.5',
              price: 199,
              isTopOfTheWeek: false,
              image: require('../assets/images/user12.jpg'),
              size: 'LArge Glass',
              crust: 'Large Ice',
              delivery: 8,
              
            },
          {
            name: 'Fawad',
            ID: 351290129210,
            Qty: '10 kg', 
            rating: '4.2',
            price: 499,
            isTopOfTheWeek: false,
            image: require('../assets/images/user11.jpg'),
            size: 'Large 15"',
            crust: 'Thin Crust',
            delivery: 45,
         
          },
        ],
      },


      {
        name: 'Sea Food',
        items: [
          {
            name: 'Fahad',
            ID: 252901921020,
            Qty: '10 kg', 
            rating: '5.0',
            price: 199,
            isTopOfTheWeek: true,
            image: require('../assets/images/user2.jpg'),
            size: 'Large 14"',
            crust: 'Thin Crust',
            delivery: 30,
         
          },
          {
            name: 'Mustafa',
            ID: 300290122180,
            Qty: '10 kg', 
            rating: '4.5',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/images/user3.jpg'),
            size: 'Large 16"',
            crust: 'Thin Cheese',
            delivery: 25,
         
          },
          {
            name: 'Kareem',
            ID: 351290129210,
            Qty: '10 kg', 
            rating: '4.2',
            price: 499,
            isTopOfTheWeek: false,
            image: require('../assets/images/user4.jpg'),
            size: 'Large 15"',
            crust: 'Thin Crust',
            delivery: 45,
          },
        ],
      },


      {
        name: 'Diary',
        items: [
          {
            name: 'Aslam',
            ID: 252901921020,
            Qty: '10 kg', 
            rating: '5.0',
            price: 199,
            isTopOfTheWeek: true,
            image: require('../assets/images/user10.jpg'),
            size: 'Large 14"',
            crust: 'Thin Crust',
            delivery: 30,
         
          },
          {
            name: 'Khurram',
            ID: 300290122180,
            Qty: '10 kg', 
            rating: '4.5',
            price: 299,
            isTopOfTheWeek: false,
            image: require('../assets/images/user6.jpg'),
            size: 'Large 16"',
            crust: 'Thin Cheese',
            delivery: 25,
         
          },
          {
            name: 'Ikram',
            ID: 351290129210,
            Qty: '10 kg', 
            rating: '4.2',
            price: 499,
            isTopOfTheWeek: false,
            image: require('../assets/images/user15.jpg'),
            size: 'Large 15"',
            crust: 'Thin Crust',
            delivery: 45,
         
          },
        ],
      },

    {
      name: 'Spices',
      items: [
        {
          name: 'Ehsan',
          ID: 20182301920,
          Qty: '10 kg', 
          rating: '5.0',
          price: 299,
          isTopOfTheWeek: true,
          image: require('../assets/images/user11.jpg'),
          size: 'Medium Glass',
          crust: 'Small Ice',
          delivery: 10,
         
        },
        {
          name: 'Asif',
          ID: 50172637120,
          Qty: '10 kg', 
          rating: '4.5',
          price: 199,
          isTopOfTheWeek: false,
          image: require('../assets/images/user12.jpg'),
          size: 'LArge Glass',
          crust: 'Large Ice',
          delivery: 8,
          
        },
        {
          name: 'Usama',
          ID: 15082191219,
          Qty: '10 kg', 
          rating: '4.2',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../assets/images/user2.jpg'),
          size: 'Large Glass',
          crust: 'Small Ice',
          delivery: 5,
         
        },
      ],
    },
  ];

  
